### PR TITLE
[JENKINS-71922] Support Java 21

### PR DESCRIPTION
**Pull request by alecharp**
Related to [JENKINS-71922](https://issues.jenkins.io/browse/JENKINS-71922)

The usage of Lombok was introduced in https://github.com/jenkinsci/google-oauth-plugin/commit/5972f753b7c3b92f863f1a7c3e48f66eb604174e.
The dependency was used only to remove a few lines of code which can generally be generated by any IDE. 

There is no usages of the library outside of the `CredentialsListBoxModel` class, so it seems a bit overkill to use the library. Removing it to be compatible with Java 21 seems quicker.

### Testing done

Ran `mvn verify` with Java 21, no issue.
Ran `mvn hpi:run` using Java 21 but faced issue when trying to use the plugin in Google Compute Engine where creating a compute-engine node in Jenkins yields an issue about not finding `configure-entries.jelly` for `ComputeEngineInstance` class.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by alecharp** [comment]
To be useful, the PR should be reopened by a maintainer or an admin so that the `Jenkinsfile` is used.

**Review by basil — APPROVED** [review]
Replayed the run with Jenkinsfile changes here:

https://ci.jenkins.io/job/Plugins/job/google-oauth-plugin/job/PR-184/3/

Build is green

**Comment by alecharp** [comment]
@jenkinsci/google-oauth-plugin-developers do you think this could be merged and released?

**Comment by jtnord** [comment]
https://github.com/jenkinsci/google-oauth-plugin/releases/tag/google-oauth-plugin-1.0.11

**Pull request merged**
