### PR TITLE
update google-api to 1.22.0

### PR DESCRIPTION
**Pull request by bvoss**
update google-api to support KMS in other jenkins plugins
see #7

### CODE REVIEW

**Comment by bvoss** [comment]
Sorry, I can't get the local build running with the old jenkins-plugin version at all.
I change it back and we'll see how it went.

**Comment by naphthalene** [comment]
I don't know if this project is being maintained. It might help to add an issue in the Jenkins Jira tracker as well.

**Comment by bvoss** [comment]
Thanks for the hint.
I opened this [Jira issue](https://issues.jenkins-ci.org/browse/JENKINS-43479)

**Comment by astroilov** [comment]
Hi! I'll take a look at this change. In the meantime - we do require that authors of contributing code sign a contributor license agreement (CLA). You (or your employer) retain the copyright to your contribution,
this simply gives us permission to use and redistribute your contributions as
part of the project. It looks like you don't yet have a CLA on file; you can do so easily at https://cla.developers.google.com/. Alternately, if you should already have a CLA, let me know and I'll investigate further.

**Comment by bvoss** [comment]
Just signed.

**Comment by bvoss** [comment]
Is there anything else I need to do?

**Comment by astroilov** [comment]
No, this looks good. I'll prep this for a release.

**Comment by astroilov** [comment]
FYI, this is in version 0.5, which has now been released.

**Comment by bvoss** [comment]
Thanks!
I switch back to this official release and everything works fine.

**Pull request merged**
